#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# export SET KRE_APPBASE="$DIR/approot/packages/OmniSharp/1.0.0/root"
export PATH=$PATH:/usr/local/bin # this is required for the users of the Homebrew Mono package

exec mono "$DIR/OmniSharp.exe" "$@"
